@url = http://localhost:4000/api

### Extrato
GET {{url}}/clients/1/extrato

### Transaction
POST {{url}}/clients/1/transacoes
Content-Type: application/json

{
    "valor": 200000,
    "tipo": "c",
    "descricao": "descricao"
}