@url = http://localhost:9999

### Extrato
GET {{url}}/clientes/2/extrato

### Transaction
POST {{url}}/clientes/2/transacoes
Content-Type: application/json

{"valor": 6784, "tipo": "c", "descricao": "C2Ecvha34z"}