version: '3.5'

services:
  api01: &api
    hostname: api01
    build:
      context: ..
    environment:
      - DATABASE_URL=postgresql://admin:123@db/rinha
      - POOL_SIZE=30
      - PORT=4000
      - SECRET_KEY_BASE=123
    ports:
      - "8081:4000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
  api02:
    <<: *api 
    depends_on:
      - api01
    hostname: api02
    ports:
      - "8082:4000"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

    